### ISSUE TITLE
TeamCity Failed to start build runner 'allureReportGeneratorRunner'

### ISSUE THREAD

**Issue by promiteyka** [allure-framework/allure-teamcity#103]
There is a problem with the plugin, it looks like problem started after the upgrade of the Teamcity to 2019.2.4 version. The problem does not always occur, sometimes the runner does not start and sometimes it works correctly.
**As agents we use redhat7. 
Teamcity version is 2019.2.4.
Allure plugin version is 2.10.
allure-commandline version is 2.13.1**
The stackrace from build below:
Step xxx: Generate Allure Report (Allure Report)
Search allure history information in xxx
Coping allure history information from xxx
Search allure history information in xxx
Allure history information already exists ...
  java.lang.NoClassDefFoundError: Could not initialize class org.apache.commons.lang.SystemUtils
  at io.qameta.allure.teamcity.AllureBuildServiceAdapter.getExecutableName(AllureBuildServiceAdapter.java:419)
  at io.qameta.allure.teamcity.AllureBuildServiceAdapter.getProgramPath(AllureBuildServiceAdapter.java:388)
  at io.qameta.allure.teamcity.AllureBuildServiceAdapter.makeProgramCommandLine(AllureBuildServiceAdapter.java:137)
  at jetbrains.buildServer.agent.runner2.SingleCommandLineBuildSessionAdapter.makeProgramCommandLine(SingleCommandLineBuildSessionAdapter.java:54)
  at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.executeProcess(GenericCommandLineBuildProcess.java:79)
  at jetbrains.buildServer.agent.runner2.GenericCommandLineBuildProcess.waitFor(GenericCommandLineBuildProcess.java:270)
  at jetbrains.buildServer.agent.impl.buildStages.runnerStages.start.CallRunnerStage.doBuildStage(CallRunnerStage.java:59)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:25)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor$1.callStage(RunnerStagesExecutor.java:18)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
  at jetbrains.buildServer.agent.impl.buildStages.RunnerStagesExecutor.doStages(RunnerStagesExecutor.java:18)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.RunnerContextExecutor.callRunnerStages(RunnerContextExecutor.java:43)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.StepExecutor.processNextStep(StepExecutor.java:25)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeRunnerStep(ForEachBuildRunnerStage.java:138)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.runStep(ForEachBuildRunnerStage.java:123)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.executeBuildRunners(ForEachBuildRunnerStage.java:83)
  at jetbrains.buildServer.agent.impl.buildStages.startStages.steps.ForEachBuildRunnerStage.doBuildStage(ForEachBuildRunnerStage.java:44)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
  at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
  at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:79)
  at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:312)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:55)
  at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:275)
  at java.lang.Thread.run(Thread.java:748)
Failed to start build runner 'allureReportGeneratorRunner'
Step Generate Allure Report (Allure Report) failed with unexpected error

**Comment by promiteyka** [comment]
Maybe updating the Teamcity is just a coincidence in time.

**Comment by promiteyka** [comment]
is there any news?

**Comment by vbragin** [comment]
there was an update to org.apache.commons.lang3.SystemUtils
